### PR TITLE
Added support for SystemAssigned identity

### PR DESCRIPTION
**Pull request by j-rewerts**
Due to the issue discussed [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/7787), SystemAssigned MI don't have their object IDs populated on data.azurerm_client_config.current. This PR will allow a caller to provide the deployment object ID in a variable if needed.

### CODE REVIEW

**Review by murggu — CHANGES_REQUESTED** [review]
@j-rewerts we've been working on allowing for external PR (from forked repos). Would you mind syncing your forked repo with the latest changes here?

**Comment by jdocampo** [comment]
Hi @j-rewerts it seems that in the current version of azurerm we are using, 3.45.0, this issue is resolved.
I have tried with version 3.43.0 and I could reproduce the error (this is a VM with User Assigned Managed Identity):

```
terraform {

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 3.43.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data azurerm_client_config current {}

output current_client_config {
    value = data.azurerm_client_config.current
}
```
image

But this is the test with 3.45.0:
image

Seems to be fixed since v3.44.1:
https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.44.1
https://github.com/hashicorp/terraform-provider-azurerm/pull/20523

**Comment by j-rewerts** [comment]
UA MI should work but I don't believe System Assigned will. Any chance you could try reproducing with a SAMI?

**Comment by jdocampo** [comment]
Hi @j-rewerts I have tested with System Assigned as well, seems to be working:
image
image

**Comment by j-rewerts** [comment]
Ah my mistake! Closing.

**Pull request closed without merging**
