### PR TITLE
add CMK support for Synapse module

### LINKED ISSUE #32: Add support for CMK in Synapse module
The Synapse module doesn't have the option to use a CMK to encrypt data at rest.

https://learn.microsoft.com/en-us/azure/synapse-analytics/security/workspaces-encryption#encryption-of-data-at-rest

The example of that in the azurerm Terraform provider is:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace#example-usage---creating-a-workspace-with-customer-managed-key-and-azure-ad-admin

Thank you.

### PR DESCRIPTION
**Pull request by josejfb**
Resolves #32 

Adding CMK support for Synapse workspace module so there's the option to enable double encryption at rest at the time of the workspace creation. More info: https://learn.microsoft.com/en-us/azure/synapse-analytics/security/workspaces-encryption#encryption-of-data-at-rest

Implementation follows the `azurerm` Terraform example: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace#example-usage---creating-a-workspace-with-customer-managed-key-and-azure-ad-admin

### CODE REVIEW

**Comment by josejfb** [comment]
@microsoft-github-policy-service agree

**Comment by josejfb** [comment]
Hi @murggu. One of the checks failed and it seems to me that failed installing `tfsec` (somehow it got a 404 when accessing the `tfsec` repo) or at least that's my understanding of the error. Did you experience this problem before? How could I rerun that check? Thank you.

**Comment by murggu** [comment]
@josejfb the issue could be related to how GH_TOKEN is set up on .yml files. Could you please change ``GH_TOKEN: ${{ secrets.GH_TOKEN }}`` by  ``GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}`` on your synapse-workspace.yml file?

A quick note on secrets.GITHUB_TOKEN - this is created automatically for you when you start using Actions.

**Comment by josejfb** [comment]
Hi @murggu. The previous error is now solved (thanks for the hint) and I got now another one. Somehow the test is not running `az login` so the Terraform backend initialization is failing. 

```
TestModule 2022-12-14T08:29:14Z logger.go:66: Initializing the backend...
TestModule 2022-12-14T08:29:18Z logger.go:66: ╷
TestModule 2022-12-14T08:29:18Z logger.go:66: │ Error: Error building ARM Config: obtain subscription() from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
```

Reviewing the code I see that the test sets the environment ARM variables from GitHub secrets but it seems that either they are not set or maybe because of my user permissions those secrets can't be read so the code tries to get the credentials from the Azure CLI credentials that are obviously not present.

Could you please take a look at this? Thank you very much.

**Comment by murggu** [comment]
@josejfb this seems related to secrets access. Let me have a look and get back to you. By the way, would you mind changing AzureRm version to 3.36.0 in providers.tf? This is the version included in upcoming v1.2.0.

**Review by murggu — APPROVED** [review]

**Review by murggu — CHANGES_REQUESTED** [review]
@josejfb we have been working on allowing external PRs. Would you mind syncing you forked repo with the latest changes so we can see if your PR passes the tests?

**Comment by murggu** [comment]
Closing this PR after 2-3 months.

**Pull request closed without merging**
